# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Id_departamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=10)),
            ],
        ),
    ]
